version: "3"

services:
  post-app:
    build:
      context: ./post-app
      dockerfile: ../docker/app/Dockerfile.local
    container_name: pesh-snsc-api_post-app
    volumes:
      - .:/go/src
    ports:
      - "8081:8081"
    tty: true
    env_file:
      - "./post-app/.env.local.compose"

networks:
  default:
    name: pesh-snsc_default
    external: true

