openapi: 3.0.3
info:
  version: 0.0.1
  title: post-app
tags:
  - name: post
    description: 投稿情報に関するエンドポイント
paths:
  /posts/{postId}:
    get:
      summary: 投稿詳細情報の取得
      description: 指定されたIDの投稿詳細情報を取得する
      operationId: getPost
      tags:
        - post
      parameters:
        - name: postId
          in: path
          required: true
          description: 投稿ID
          example: 000POSTID001
          schema:
            type: integer
            x-go-type: uint64
      responses:
        "200":
          $ref: "#/components/responses/GetPostResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerError"

components:
  schemas:
    Post:
      type: object
      description: 投稿情報
      required:
        - id
        - title
        - likeCount
        - commentsCount
        - caption
        - permalink
        - postedAt
      properties:
        id:
          type: integer
          description: 投稿ID
          example: 000POSTID001
          x-go-type: uint64
        title:
          type: string
          description: 投稿タイトル
          example: 投稿タイトル
        likeCount:
          type: integer
          description: いいね数
          example: 100
          x-go-type: uint32
        commentsCount:
          type: integer
          description: コメント数
          example: 100
          x-go-type: uint32
        caption:
          type: string
          description: 投稿詳細文
          example: 投稿詳細文
        permalink:
          type: string
          description: https://example.com/000POSTID001
          format: uri
        postedAt:
          type: string
          description: 投稿日時
          example: "2020-01-31T23:59:59+09:00"
          format: date-time

    DomainError:
      type: object
      description: エラーレスポンス
      required:
        - message
      properties:
        message:
          type: string
          example: Error Messages

  responses:
    GetPostResponse:
      description: 投稿取得成功時レスポンス
      content:
        application/json:
          schema:
            type: object
            description: 投稿詳細レスポンス
            required:
              - post
            properties:
              post:
                $ref: "#/components/schemas/Post"

    BadRequest:
      description: 400番台エラーレスポンス
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/DomainError"

    InternalServerError:
      description: 500番台エラーレスポンス
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/DomainError"
