version: "3"

services:
  api:
    build:
      context: .
      dockerfile: ../docker/api/Dockerfile
    container_name: pesh-snsc-post_api
    command: go run main.go
    volumes:
      - .:/go/src
    ports:
      - "8080:8080"
