output   = "models"
pkgname = "models"
no-tests = true

[psql]
dbname = "postgres"
host   = "0.0.0.0"
port   = 5432
user   = "postgres"
pass   = "postgres"
sslmode = "disable"
blacklist = [
    "auth_group",
    "auth_group_permissions",
    "auth_permission",
    "django_admin_log",
    "django_content_type",
    "django_migrations",
    "django_session",
]
