// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Post                    string
	PostMedia               string
	PostProduct             string
	PostProductRelationship string
	Site                    string
	SiteOwnership           string
	SNS                     string
	SNSAPIAccount           string
	SNSUserAccount          string
	SNSCUser                string
	SNSCUserGroups          string
	SNSCUserUserPermissions string
}{
	Post:                    "post",
	PostMedia:               "post_media",
	PostProduct:             "post_product",
	PostProductRelationship: "post_product_relationship",
	Site:                    "site",
	SiteOwnership:           "site_ownership",
	SNS:                     "sns",
	SNSAPIAccount:           "sns_api_account",
	SNSUserAccount:          "sns_user_account",
	SNSCUser:                "snsc_user",
	SNSCUserGroups:          "snsc_user_groups",
	SNSCUserUserPermissions: "snsc_user_user_permissions",
}
