// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// SNSCUserGroup is an object representing the database table.
type SNSCUserGroup struct {
	ID         int64 `boil:"id" json:"id" toml:"id" yaml:"id"`
	SnscuserID int64 `boil:"snscuser_id" json:"snscuser_id" toml:"snscuser_id" yaml:"snscuser_id"`
	GroupID    int   `boil:"group_id" json:"group_id" toml:"group_id" yaml:"group_id"`

	R *snscUserGroupR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L snscUserGroupL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var SNSCUserGroupColumns = struct {
	ID         string
	SnscuserID string
	GroupID    string
}{
	ID:         "id",
	SnscuserID: "snscuser_id",
	GroupID:    "group_id",
}

var SNSCUserGroupTableColumns = struct {
	ID         string
	SnscuserID string
	GroupID    string
}{
	ID:         "snsc_user_groups.id",
	SnscuserID: "snsc_user_groups.snscuser_id",
	GroupID:    "snsc_user_groups.group_id",
}

// Generated where

type whereHelperint struct{ field string }

func (w whereHelperint) EQ(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint) NEQ(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint) LT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint) LTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint) GT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint) GTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint) IN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint) NIN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

var SNSCUserGroupWhere = struct {
	ID         whereHelperint64
	SnscuserID whereHelperint64
	GroupID    whereHelperint
}{
	ID:         whereHelperint64{field: "\"snsc_user_groups\".\"id\""},
	SnscuserID: whereHelperint64{field: "\"snsc_user_groups\".\"snscuser_id\""},
	GroupID:    whereHelperint{field: "\"snsc_user_groups\".\"group_id\""},
}

// SNSCUserGroupRels is where relationship names are stored.
var SNSCUserGroupRels = struct {
	Snscuser string
}{
	Snscuser: "Snscuser",
}

// snscUserGroupR is where relationships are stored.
type snscUserGroupR struct {
	Snscuser *SNSCUser `boil:"Snscuser" json:"Snscuser" toml:"Snscuser" yaml:"Snscuser"`
}

// NewStruct creates a new relationship struct
func (*snscUserGroupR) NewStruct() *snscUserGroupR {
	return &snscUserGroupR{}
}

func (r *snscUserGroupR) GetSnscuser() *SNSCUser {
	if r == nil {
		return nil
	}
	return r.Snscuser
}

// snscUserGroupL is where Load methods for each relationship are stored.
type snscUserGroupL struct{}

var (
	snscUserGroupAllColumns            = []string{"id", "snscuser_id", "group_id"}
	snscUserGroupColumnsWithoutDefault = []string{"snscuser_id", "group_id"}
	snscUserGroupColumnsWithDefault    = []string{"id"}
	snscUserGroupPrimaryKeyColumns     = []string{"id"}
	snscUserGroupGeneratedColumns      = []string{}
)

type (
	// SNSCUserGroupSlice is an alias for a slice of pointers to SNSCUserGroup.
	// This should almost always be used instead of []SNSCUserGroup.
	SNSCUserGroupSlice []*SNSCUserGroup
	// SNSCUserGroupHook is the signature for custom SNSCUserGroup hook methods
	SNSCUserGroupHook func(context.Context, boil.ContextExecutor, *SNSCUserGroup) error

	snscUserGroupQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	snscUserGroupType                 = reflect.TypeOf(&SNSCUserGroup{})
	snscUserGroupMapping              = queries.MakeStructMapping(snscUserGroupType)
	snscUserGroupPrimaryKeyMapping, _ = queries.BindMapping(snscUserGroupType, snscUserGroupMapping, snscUserGroupPrimaryKeyColumns)
	snscUserGroupInsertCacheMut       sync.RWMutex
	snscUserGroupInsertCache          = make(map[string]insertCache)
	snscUserGroupUpdateCacheMut       sync.RWMutex
	snscUserGroupUpdateCache          = make(map[string]updateCache)
	snscUserGroupUpsertCacheMut       sync.RWMutex
	snscUserGroupUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var snscUserGroupAfterSelectMu sync.Mutex
var snscUserGroupAfterSelectHooks []SNSCUserGroupHook

var snscUserGroupBeforeInsertMu sync.Mutex
var snscUserGroupBeforeInsertHooks []SNSCUserGroupHook
var snscUserGroupAfterInsertMu sync.Mutex
var snscUserGroupAfterInsertHooks []SNSCUserGroupHook

var snscUserGroupBeforeUpdateMu sync.Mutex
var snscUserGroupBeforeUpdateHooks []SNSCUserGroupHook
var snscUserGroupAfterUpdateMu sync.Mutex
var snscUserGroupAfterUpdateHooks []SNSCUserGroupHook

var snscUserGroupBeforeDeleteMu sync.Mutex
var snscUserGroupBeforeDeleteHooks []SNSCUserGroupHook
var snscUserGroupAfterDeleteMu sync.Mutex
var snscUserGroupAfterDeleteHooks []SNSCUserGroupHook

var snscUserGroupBeforeUpsertMu sync.Mutex
var snscUserGroupBeforeUpsertHooks []SNSCUserGroupHook
var snscUserGroupAfterUpsertMu sync.Mutex
var snscUserGroupAfterUpsertHooks []SNSCUserGroupHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *SNSCUserGroup) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range snscUserGroupAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *SNSCUserGroup) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range snscUserGroupBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *SNSCUserGroup) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range snscUserGroupAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *SNSCUserGroup) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range snscUserGroupBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *SNSCUserGroup) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range snscUserGroupAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *SNSCUserGroup) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range snscUserGroupBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *SNSCUserGroup) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range snscUserGroupAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *SNSCUserGroup) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range snscUserGroupBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *SNSCUserGroup) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range snscUserGroupAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddSNSCUserGroupHook registers your hook function for all future operations.
func AddSNSCUserGroupHook(hookPoint boil.HookPoint, snscUserGroupHook SNSCUserGroupHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		snscUserGroupAfterSelectMu.Lock()
		snscUserGroupAfterSelectHooks = append(snscUserGroupAfterSelectHooks, snscUserGroupHook)
		snscUserGroupAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		snscUserGroupBeforeInsertMu.Lock()
		snscUserGroupBeforeInsertHooks = append(snscUserGroupBeforeInsertHooks, snscUserGroupHook)
		snscUserGroupBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		snscUserGroupAfterInsertMu.Lock()
		snscUserGroupAfterInsertHooks = append(snscUserGroupAfterInsertHooks, snscUserGroupHook)
		snscUserGroupAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		snscUserGroupBeforeUpdateMu.Lock()
		snscUserGroupBeforeUpdateHooks = append(snscUserGroupBeforeUpdateHooks, snscUserGroupHook)
		snscUserGroupBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		snscUserGroupAfterUpdateMu.Lock()
		snscUserGroupAfterUpdateHooks = append(snscUserGroupAfterUpdateHooks, snscUserGroupHook)
		snscUserGroupAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		snscUserGroupBeforeDeleteMu.Lock()
		snscUserGroupBeforeDeleteHooks = append(snscUserGroupBeforeDeleteHooks, snscUserGroupHook)
		snscUserGroupBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		snscUserGroupAfterDeleteMu.Lock()
		snscUserGroupAfterDeleteHooks = append(snscUserGroupAfterDeleteHooks, snscUserGroupHook)
		snscUserGroupAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		snscUserGroupBeforeUpsertMu.Lock()
		snscUserGroupBeforeUpsertHooks = append(snscUserGroupBeforeUpsertHooks, snscUserGroupHook)
		snscUserGroupBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		snscUserGroupAfterUpsertMu.Lock()
		snscUserGroupAfterUpsertHooks = append(snscUserGroupAfterUpsertHooks, snscUserGroupHook)
		snscUserGroupAfterUpsertMu.Unlock()
	}
}

// One returns a single snscUserGroup record from the query.
func (q snscUserGroupQuery) One(ctx context.Context, exec boil.ContextExecutor) (*SNSCUserGroup, error) {
	o := &SNSCUserGroup{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for snsc_user_groups")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all SNSCUserGroup records from the query.
func (q snscUserGroupQuery) All(ctx context.Context, exec boil.ContextExecutor) (SNSCUserGroupSlice, error) {
	var o []*SNSCUserGroup

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to SNSCUserGroup slice")
	}

	if len(snscUserGroupAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all SNSCUserGroup records in the query.
func (q snscUserGroupQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count snsc_user_groups rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q snscUserGroupQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if snsc_user_groups exists")
	}

	return count > 0, nil
}

// Snscuser pointed to by the foreign key.
func (o *SNSCUserGroup) Snscuser(mods ...qm.QueryMod) snscUserQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.SnscuserID),
	}

	queryMods = append(queryMods, mods...)

	return SNSCUsers(queryMods...)
}

// LoadSnscuser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (snscUserGroupL) LoadSnscuser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeSNSCUserGroup interface{}, mods queries.Applicator) error {
	var slice []*SNSCUserGroup
	var object *SNSCUserGroup

	if singular {
		var ok bool
		object, ok = maybeSNSCUserGroup.(*SNSCUserGroup)
		if !ok {
			object = new(SNSCUserGroup)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeSNSCUserGroup)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeSNSCUserGroup))
			}
		}
	} else {
		s, ok := maybeSNSCUserGroup.(*[]*SNSCUserGroup)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeSNSCUserGroup)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeSNSCUserGroup))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &snscUserGroupR{}
		}
		args[object.SnscuserID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &snscUserGroupR{}
			}

			args[obj.SnscuserID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`snsc_user`),
		qm.WhereIn(`snsc_user.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load SNSCUser")
	}

	var resultSlice []*SNSCUser
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice SNSCUser")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for snsc_user")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for snsc_user")
	}

	if len(snscUserAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Snscuser = foreign
		if foreign.R == nil {
			foreign.R = &snscUserR{}
		}
		foreign.R.SnscuserSNSCUserGroups = append(foreign.R.SnscuserSNSCUserGroups, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.SnscuserID == foreign.ID {
				local.R.Snscuser = foreign
				if foreign.R == nil {
					foreign.R = &snscUserR{}
				}
				foreign.R.SnscuserSNSCUserGroups = append(foreign.R.SnscuserSNSCUserGroups, local)
				break
			}
		}
	}

	return nil
}

// SetSnscuser of the snscUserGroup to the related item.
// Sets o.R.Snscuser to related.
// Adds o to related.R.SnscuserSNSCUserGroups.
func (o *SNSCUserGroup) SetSnscuser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *SNSCUser) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"snsc_user_groups\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"snscuser_id"}),
		strmangle.WhereClause("\"", "\"", 2, snscUserGroupPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.SnscuserID = related.ID
	if o.R == nil {
		o.R = &snscUserGroupR{
			Snscuser: related,
		}
	} else {
		o.R.Snscuser = related
	}

	if related.R == nil {
		related.R = &snscUserR{
			SnscuserSNSCUserGroups: SNSCUserGroupSlice{o},
		}
	} else {
		related.R.SnscuserSNSCUserGroups = append(related.R.SnscuserSNSCUserGroups, o)
	}

	return nil
}

// SNSCUserGroups retrieves all the records using an executor.
func SNSCUserGroups(mods ...qm.QueryMod) snscUserGroupQuery {
	mods = append(mods, qm.From("\"snsc_user_groups\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"snsc_user_groups\".*"})
	}

	return snscUserGroupQuery{q}
}

// FindSNSCUserGroup retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindSNSCUserGroup(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*SNSCUserGroup, error) {
	snscUserGroupObj := &SNSCUserGroup{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"snsc_user_groups\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, snscUserGroupObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from snsc_user_groups")
	}

	if err = snscUserGroupObj.doAfterSelectHooks(ctx, exec); err != nil {
		return snscUserGroupObj, err
	}

	return snscUserGroupObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *SNSCUserGroup) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no snsc_user_groups provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(snscUserGroupColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	snscUserGroupInsertCacheMut.RLock()
	cache, cached := snscUserGroupInsertCache[key]
	snscUserGroupInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			snscUserGroupAllColumns,
			snscUserGroupColumnsWithDefault,
			snscUserGroupColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(snscUserGroupType, snscUserGroupMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(snscUserGroupType, snscUserGroupMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"snsc_user_groups\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"snsc_user_groups\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into snsc_user_groups")
	}

	if !cached {
		snscUserGroupInsertCacheMut.Lock()
		snscUserGroupInsertCache[key] = cache
		snscUserGroupInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the SNSCUserGroup.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *SNSCUserGroup) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	snscUserGroupUpdateCacheMut.RLock()
	cache, cached := snscUserGroupUpdateCache[key]
	snscUserGroupUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			snscUserGroupAllColumns,
			snscUserGroupPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update snsc_user_groups, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"snsc_user_groups\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, snscUserGroupPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(snscUserGroupType, snscUserGroupMapping, append(wl, snscUserGroupPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update snsc_user_groups row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for snsc_user_groups")
	}

	if !cached {
		snscUserGroupUpdateCacheMut.Lock()
		snscUserGroupUpdateCache[key] = cache
		snscUserGroupUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q snscUserGroupQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for snsc_user_groups")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for snsc_user_groups")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o SNSCUserGroupSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), snscUserGroupPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"snsc_user_groups\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, snscUserGroupPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in snscUserGroup slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all snscUserGroup")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *SNSCUserGroup) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no snsc_user_groups provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(snscUserGroupColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	snscUserGroupUpsertCacheMut.RLock()
	cache, cached := snscUserGroupUpsertCache[key]
	snscUserGroupUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			snscUserGroupAllColumns,
			snscUserGroupColumnsWithDefault,
			snscUserGroupColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			snscUserGroupAllColumns,
			snscUserGroupPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert snsc_user_groups, could not build update column list")
		}

		ret := strmangle.SetComplement(snscUserGroupAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(snscUserGroupPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert snsc_user_groups, could not build conflict column list")
			}

			conflict = make([]string, len(snscUserGroupPrimaryKeyColumns))
			copy(conflict, snscUserGroupPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"snsc_user_groups\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(snscUserGroupType, snscUserGroupMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(snscUserGroupType, snscUserGroupMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert snsc_user_groups")
	}

	if !cached {
		snscUserGroupUpsertCacheMut.Lock()
		snscUserGroupUpsertCache[key] = cache
		snscUserGroupUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single SNSCUserGroup record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *SNSCUserGroup) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no SNSCUserGroup provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), snscUserGroupPrimaryKeyMapping)
	sql := "DELETE FROM \"snsc_user_groups\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from snsc_user_groups")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for snsc_user_groups")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q snscUserGroupQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no snscUserGroupQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from snsc_user_groups")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for snsc_user_groups")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o SNSCUserGroupSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(snscUserGroupBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), snscUserGroupPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"snsc_user_groups\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, snscUserGroupPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from snscUserGroup slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for snsc_user_groups")
	}

	if len(snscUserGroupAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *SNSCUserGroup) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindSNSCUserGroup(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SNSCUserGroupSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := SNSCUserGroupSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), snscUserGroupPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"snsc_user_groups\".* FROM \"snsc_user_groups\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, snscUserGroupPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in SNSCUserGroupSlice")
	}

	*o = slice

	return nil
}

// SNSCUserGroupExists checks if the SNSCUserGroup row exists.
func SNSCUserGroupExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"snsc_user_groups\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if snsc_user_groups exists")
	}

	return exists, nil
}

// Exists checks if the SNSCUserGroup row exists.
func (o *SNSCUserGroup) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return SNSCUserGroupExists(ctx, exec, o.ID)
}
